package com.rbcdemo.dao.mapper;

import com.rbcdemo.dao.entity.Rolemenu;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RolemenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated
     */
    int insert(Rolemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated
     */
    Rolemenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated
     */
    List<Rolemenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolemenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Rolemenu record);

    List<Rolemenu> selectbyroleids(List<Integer> ids);
}