package com.rbcdemo.dao.mapper;

import com.rbcdemo.dao.entity.Role;
import com.rbcdemo.dao.entity.Userrole;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated
     */
    int insert(Userrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated
     */
    Userrole selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated
     */
    List<Userrole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Userrole record);

    int insetBatch(List<Userrole> urList);

    List<Userrole> getUserRoleIds(int userid);
}